// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Profile.API.Data;

#nullable disable

namespace Profile.API.Data.Migrations
{
    [DbContext(typeof(ProfileContext))]
    [Migration("20231128135905_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Profile.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dummy Address No_1",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9687),
                            Email = "dummy1@gmail.com",
                            FirstName = "DummyName_1",
                            IsDeleted = false,
                            LastName = "DummyLastName_1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Dummy Address No_2",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9739),
                            Email = "dummy2@gmail.com",
                            FirstName = "DummyName_2",
                            IsDeleted = false,
                            LastName = "DummyLastName_2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Dummy Address No_3",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9742),
                            Email = "dummy3@gmail.com",
                            FirstName = "DummyName_3",
                            IsDeleted = false,
                            LastName = "DummyLastName_3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Dummy Address No_4",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9743),
                            Email = "dummy4@gmail.com",
                            FirstName = "DummyName_4",
                            IsDeleted = false,
                            LastName = "DummyLastName_4"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Dummy Address No_5",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9745),
                            Email = "dummy5@gmail.com",
                            FirstName = "DummyName_5",
                            IsDeleted = false,
                            LastName = "DummyLastName_5"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Dummy Address No_6",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9749),
                            Email = "dummy6@gmail.com",
                            FirstName = "DummyName_6",
                            IsDeleted = false,
                            LastName = "DummyLastName_6"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Dummy Address No_7",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9751),
                            Email = "dummy7@gmail.com",
                            FirstName = "DummyName_7",
                            IsDeleted = false,
                            LastName = "DummyLastName_7"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Dummy Address No_8",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9753),
                            Email = "dummy8@gmail.com",
                            FirstName = "DummyName_8",
                            IsDeleted = false,
                            LastName = "DummyLastName_8"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Dummy Address No_9",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9755),
                            Email = "dummy9@gmail.com",
                            FirstName = "DummyName_9",
                            IsDeleted = false,
                            LastName = "DummyLastName_9"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Dummy Address No_10",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9810),
                            Email = "dummy10@gmail.com",
                            FirstName = "DummyName_10",
                            IsDeleted = false,
                            LastName = "DummyLastName_10"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Dummy Address No_11",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9812),
                            Email = "dummy11@gmail.com",
                            FirstName = "DummyName_11",
                            IsDeleted = false,
                            LastName = "DummyLastName_11"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Dummy Address No_12",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9814),
                            Email = "dummy12@gmail.com",
                            FirstName = "DummyName_12",
                            IsDeleted = false,
                            LastName = "DummyLastName_12"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Dummy Address No_13",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9816),
                            Email = "dummy13@gmail.com",
                            FirstName = "DummyName_13",
                            IsDeleted = false,
                            LastName = "DummyLastName_13"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Dummy Address No_14",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9818),
                            Email = "dummy14@gmail.com",
                            FirstName = "DummyName_14",
                            IsDeleted = false,
                            LastName = "DummyLastName_14"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Dummy Address No_15",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9820),
                            Email = "dummy15@gmail.com",
                            FirstName = "DummyName_15",
                            IsDeleted = false,
                            LastName = "DummyLastName_15"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Dummy Address No_16",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9822),
                            Email = "dummy16@gmail.com",
                            FirstName = "DummyName_16",
                            IsDeleted = false,
                            LastName = "DummyLastName_16"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Dummy Address No_17",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9824),
                            Email = "dummy17@gmail.com",
                            FirstName = "DummyName_17",
                            IsDeleted = false,
                            LastName = "DummyLastName_17"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Dummy Address No_18",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9828),
                            Email = "dummy18@gmail.com",
                            FirstName = "DummyName_18",
                            IsDeleted = false,
                            LastName = "DummyLastName_18"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Dummy Address No_19",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9830),
                            Email = "dummy19@gmail.com",
                            FirstName = "DummyName_19",
                            IsDeleted = false,
                            LastName = "DummyLastName_19"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Dummy Address No_20",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9833),
                            Email = "dummy20@gmail.com",
                            FirstName = "DummyName_20",
                            IsDeleted = false,
                            LastName = "DummyLastName_20"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Dummy Address No_21",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9834),
                            Email = "dummy21@gmail.com",
                            FirstName = "DummyName_21",
                            IsDeleted = false,
                            LastName = "DummyLastName_21"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Dummy Address No_22",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9836),
                            Email = "dummy22@gmail.com",
                            FirstName = "DummyName_22",
                            IsDeleted = false,
                            LastName = "DummyLastName_22"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Dummy Address No_23",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9838),
                            Email = "dummy23@gmail.com",
                            FirstName = "DummyName_23",
                            IsDeleted = false,
                            LastName = "DummyLastName_23"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Dummy Address No_24",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9840),
                            Email = "dummy24@gmail.com",
                            FirstName = "DummyName_24",
                            IsDeleted = false,
                            LastName = "DummyLastName_24"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Dummy Address No_25",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9842),
                            Email = "dummy25@gmail.com",
                            FirstName = "DummyName_25",
                            IsDeleted = false,
                            LastName = "DummyLastName_25"
                        },
                        new
                        {
                            Id = 26,
                            Address = "Dummy Address No_26",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9844),
                            Email = "dummy26@gmail.com",
                            FirstName = "DummyName_26",
                            IsDeleted = false,
                            LastName = "DummyLastName_26"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Dummy Address No_27",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9845),
                            Email = "dummy27@gmail.com",
                            FirstName = "DummyName_27",
                            IsDeleted = false,
                            LastName = "DummyLastName_27"
                        },
                        new
                        {
                            Id = 28,
                            Address = "Dummy Address No_28",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9847),
                            Email = "dummy28@gmail.com",
                            FirstName = "DummyName_28",
                            IsDeleted = false,
                            LastName = "DummyLastName_28"
                        },
                        new
                        {
                            Id = 29,
                            Address = "Dummy Address No_29",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9869),
                            Email = "dummy29@gmail.com",
                            FirstName = "DummyName_29",
                            IsDeleted = false,
                            LastName = "DummyLastName_29"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Dummy Address No_30",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9871),
                            Email = "dummy30@gmail.com",
                            FirstName = "DummyName_30",
                            IsDeleted = false,
                            LastName = "DummyLastName_30"
                        },
                        new
                        {
                            Id = 31,
                            Address = "Dummy Address No_31",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9873),
                            Email = "dummy31@gmail.com",
                            FirstName = "DummyName_31",
                            IsDeleted = false,
                            LastName = "DummyLastName_31"
                        },
                        new
                        {
                            Id = 32,
                            Address = "Dummy Address No_32",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9875),
                            Email = "dummy32@gmail.com",
                            FirstName = "DummyName_32",
                            IsDeleted = false,
                            LastName = "DummyLastName_32"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Dummy Address No_33",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9877),
                            Email = "dummy33@gmail.com",
                            FirstName = "DummyName_33",
                            IsDeleted = false,
                            LastName = "DummyLastName_33"
                        },
                        new
                        {
                            Id = 34,
                            Address = "Dummy Address No_34",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9880),
                            Email = "dummy34@gmail.com",
                            FirstName = "DummyName_34",
                            IsDeleted = false,
                            LastName = "DummyLastName_34"
                        },
                        new
                        {
                            Id = 35,
                            Address = "Dummy Address No_35",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9882),
                            Email = "dummy35@gmail.com",
                            FirstName = "DummyName_35",
                            IsDeleted = false,
                            LastName = "DummyLastName_35"
                        },
                        new
                        {
                            Id = 36,
                            Address = "Dummy Address No_36",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9883),
                            Email = "dummy36@gmail.com",
                            FirstName = "DummyName_36",
                            IsDeleted = false,
                            LastName = "DummyLastName_36"
                        },
                        new
                        {
                            Id = 37,
                            Address = "Dummy Address No_37",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9885),
                            Email = "dummy37@gmail.com",
                            FirstName = "DummyName_37",
                            IsDeleted = false,
                            LastName = "DummyLastName_37"
                        },
                        new
                        {
                            Id = 38,
                            Address = "Dummy Address No_38",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9887),
                            Email = "dummy38@gmail.com",
                            FirstName = "DummyName_38",
                            IsDeleted = false,
                            LastName = "DummyLastName_38"
                        },
                        new
                        {
                            Id = 39,
                            Address = "Dummy Address No_39",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9889),
                            Email = "dummy39@gmail.com",
                            FirstName = "DummyName_39",
                            IsDeleted = false,
                            LastName = "DummyLastName_39"
                        },
                        new
                        {
                            Id = 40,
                            Address = "Dummy Address No_40",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9891),
                            Email = "dummy40@gmail.com",
                            FirstName = "DummyName_40",
                            IsDeleted = false,
                            LastName = "DummyLastName_40"
                        },
                        new
                        {
                            Id = 41,
                            Address = "Dummy Address No_41",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9892),
                            Email = "dummy41@gmail.com",
                            FirstName = "DummyName_41",
                            IsDeleted = false,
                            LastName = "DummyLastName_41"
                        },
                        new
                        {
                            Id = 42,
                            Address = "Dummy Address No_42",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9894),
                            Email = "dummy42@gmail.com",
                            FirstName = "DummyName_42",
                            IsDeleted = false,
                            LastName = "DummyLastName_42"
                        },
                        new
                        {
                            Id = 43,
                            Address = "Dummy Address No_43",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9896),
                            Email = "dummy43@gmail.com",
                            FirstName = "DummyName_43",
                            IsDeleted = false,
                            LastName = "DummyLastName_43"
                        },
                        new
                        {
                            Id = 44,
                            Address = "Dummy Address No_44",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9898),
                            Email = "dummy44@gmail.com",
                            FirstName = "DummyName_44",
                            IsDeleted = false,
                            LastName = "DummyLastName_44"
                        },
                        new
                        {
                            Id = 45,
                            Address = "Dummy Address No_45",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9900),
                            Email = "dummy45@gmail.com",
                            FirstName = "DummyName_45",
                            IsDeleted = false,
                            LastName = "DummyLastName_45"
                        },
                        new
                        {
                            Id = 46,
                            Address = "Dummy Address No_46",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9902),
                            Email = "dummy46@gmail.com",
                            FirstName = "DummyName_46",
                            IsDeleted = false,
                            LastName = "DummyLastName_46"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Dummy Address No_47",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9924),
                            Email = "dummy47@gmail.com",
                            FirstName = "DummyName_47",
                            IsDeleted = false,
                            LastName = "DummyLastName_47"
                        },
                        new
                        {
                            Id = 48,
                            Address = "Dummy Address No_48",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9926),
                            Email = "dummy48@gmail.com",
                            FirstName = "DummyName_48",
                            IsDeleted = false,
                            LastName = "DummyLastName_48"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Dummy Address No_49",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9928),
                            Email = "dummy49@gmail.com",
                            FirstName = "DummyName_49",
                            IsDeleted = false,
                            LastName = "DummyLastName_49"
                        },
                        new
                        {
                            Id = 50,
                            Address = "Dummy Address No_50",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9930),
                            Email = "dummy50@gmail.com",
                            FirstName = "DummyName_50",
                            IsDeleted = false,
                            LastName = "DummyLastName_50"
                        },
                        new
                        {
                            Id = 51,
                            Address = "Dummy Address No_51",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9932),
                            Email = "dummy51@gmail.com",
                            FirstName = "DummyName_51",
                            IsDeleted = false,
                            LastName = "DummyLastName_51"
                        },
                        new
                        {
                            Id = 52,
                            Address = "Dummy Address No_52",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9934),
                            Email = "dummy52@gmail.com",
                            FirstName = "DummyName_52",
                            IsDeleted = false,
                            LastName = "DummyLastName_52"
                        },
                        new
                        {
                            Id = 53,
                            Address = "Dummy Address No_53",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9936),
                            Email = "dummy53@gmail.com",
                            FirstName = "DummyName_53",
                            IsDeleted = false,
                            LastName = "DummyLastName_53"
                        },
                        new
                        {
                            Id = 54,
                            Address = "Dummy Address No_54",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9938),
                            Email = "dummy54@gmail.com",
                            FirstName = "DummyName_54",
                            IsDeleted = false,
                            LastName = "DummyLastName_54"
                        },
                        new
                        {
                            Id = 55,
                            Address = "Dummy Address No_55",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9940),
                            Email = "dummy55@gmail.com",
                            FirstName = "DummyName_55",
                            IsDeleted = false,
                            LastName = "DummyLastName_55"
                        },
                        new
                        {
                            Id = 56,
                            Address = "Dummy Address No_56",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9942),
                            Email = "dummy56@gmail.com",
                            FirstName = "DummyName_56",
                            IsDeleted = false,
                            LastName = "DummyLastName_56"
                        },
                        new
                        {
                            Id = 57,
                            Address = "Dummy Address No_57",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9943),
                            Email = "dummy57@gmail.com",
                            FirstName = "DummyName_57",
                            IsDeleted = false,
                            LastName = "DummyLastName_57"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Dummy Address No_58",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9945),
                            Email = "dummy58@gmail.com",
                            FirstName = "DummyName_58",
                            IsDeleted = false,
                            LastName = "DummyLastName_58"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Dummy Address No_59",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9947),
                            Email = "dummy59@gmail.com",
                            FirstName = "DummyName_59",
                            IsDeleted = false,
                            LastName = "DummyLastName_59"
                        },
                        new
                        {
                            Id = 60,
                            Address = "Dummy Address No_60",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9949),
                            Email = "dummy60@gmail.com",
                            FirstName = "DummyName_60",
                            IsDeleted = false,
                            LastName = "DummyLastName_60"
                        },
                        new
                        {
                            Id = 61,
                            Address = "Dummy Address No_61",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9951),
                            Email = "dummy61@gmail.com",
                            FirstName = "DummyName_61",
                            IsDeleted = false,
                            LastName = "DummyLastName_61"
                        },
                        new
                        {
                            Id = 62,
                            Address = "Dummy Address No_62",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9953),
                            Email = "dummy62@gmail.com",
                            FirstName = "DummyName_62",
                            IsDeleted = false,
                            LastName = "DummyLastName_62"
                        },
                        new
                        {
                            Id = 63,
                            Address = "Dummy Address No_63",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9954),
                            Email = "dummy63@gmail.com",
                            FirstName = "DummyName_63",
                            IsDeleted = false,
                            LastName = "DummyLastName_63"
                        },
                        new
                        {
                            Id = 64,
                            Address = "Dummy Address No_64",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9956),
                            Email = "dummy64@gmail.com",
                            FirstName = "DummyName_64",
                            IsDeleted = false,
                            LastName = "DummyLastName_64"
                        },
                        new
                        {
                            Id = 65,
                            Address = "Dummy Address No_65",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9958),
                            Email = "dummy65@gmail.com",
                            FirstName = "DummyName_65",
                            IsDeleted = false,
                            LastName = "DummyLastName_65"
                        },
                        new
                        {
                            Id = 66,
                            Address = "Dummy Address No_66",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9981),
                            Email = "dummy66@gmail.com",
                            FirstName = "DummyName_66",
                            IsDeleted = false,
                            LastName = "DummyLastName_66"
                        },
                        new
                        {
                            Id = 67,
                            Address = "Dummy Address No_67",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9984),
                            Email = "dummy67@gmail.com",
                            FirstName = "DummyName_67",
                            IsDeleted = false,
                            LastName = "DummyLastName_67"
                        },
                        new
                        {
                            Id = 68,
                            Address = "Dummy Address No_68",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9986),
                            Email = "dummy68@gmail.com",
                            FirstName = "DummyName_68",
                            IsDeleted = false,
                            LastName = "DummyLastName_68"
                        },
                        new
                        {
                            Id = 69,
                            Address = "Dummy Address No_69",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9988),
                            Email = "dummy69@gmail.com",
                            FirstName = "DummyName_69",
                            IsDeleted = false,
                            LastName = "DummyLastName_69"
                        },
                        new
                        {
                            Id = 70,
                            Address = "Dummy Address No_70",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9990),
                            Email = "dummy70@gmail.com",
                            FirstName = "DummyName_70",
                            IsDeleted = false,
                            LastName = "DummyLastName_70"
                        },
                        new
                        {
                            Id = 71,
                            Address = "Dummy Address No_71",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9991),
                            Email = "dummy71@gmail.com",
                            FirstName = "DummyName_71",
                            IsDeleted = false,
                            LastName = "DummyLastName_71"
                        },
                        new
                        {
                            Id = 72,
                            Address = "Dummy Address No_72",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9993),
                            Email = "dummy72@gmail.com",
                            FirstName = "DummyName_72",
                            IsDeleted = false,
                            LastName = "DummyLastName_72"
                        },
                        new
                        {
                            Id = 73,
                            Address = "Dummy Address No_73",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9995),
                            Email = "dummy73@gmail.com",
                            FirstName = "DummyName_73",
                            IsDeleted = false,
                            LastName = "DummyLastName_73"
                        },
                        new
                        {
                            Id = 74,
                            Address = "Dummy Address No_74",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9997),
                            Email = "dummy74@gmail.com",
                            FirstName = "DummyName_74",
                            IsDeleted = false,
                            LastName = "DummyLastName_74"
                        },
                        new
                        {
                            Id = 75,
                            Address = "Dummy Address No_75",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 834, DateTimeKind.Local).AddTicks(9999),
                            Email = "dummy75@gmail.com",
                            FirstName = "DummyName_75",
                            IsDeleted = false,
                            LastName = "DummyLastName_75"
                        },
                        new
                        {
                            Id = 76,
                            Address = "Dummy Address No_76",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(1),
                            Email = "dummy76@gmail.com",
                            FirstName = "DummyName_76",
                            IsDeleted = false,
                            LastName = "DummyLastName_76"
                        },
                        new
                        {
                            Id = 77,
                            Address = "Dummy Address No_77",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(2),
                            Email = "dummy77@gmail.com",
                            FirstName = "DummyName_77",
                            IsDeleted = false,
                            LastName = "DummyLastName_77"
                        },
                        new
                        {
                            Id = 78,
                            Address = "Dummy Address No_78",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(4),
                            Email = "dummy78@gmail.com",
                            FirstName = "DummyName_78",
                            IsDeleted = false,
                            LastName = "DummyLastName_78"
                        },
                        new
                        {
                            Id = 79,
                            Address = "Dummy Address No_79",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(6),
                            Email = "dummy79@gmail.com",
                            FirstName = "DummyName_79",
                            IsDeleted = false,
                            LastName = "DummyLastName_79"
                        },
                        new
                        {
                            Id = 80,
                            Address = "Dummy Address No_80",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(8),
                            Email = "dummy80@gmail.com",
                            FirstName = "DummyName_80",
                            IsDeleted = false,
                            LastName = "DummyLastName_80"
                        },
                        new
                        {
                            Id = 81,
                            Address = "Dummy Address No_81",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(10),
                            Email = "dummy81@gmail.com",
                            FirstName = "DummyName_81",
                            IsDeleted = false,
                            LastName = "DummyLastName_81"
                        },
                        new
                        {
                            Id = 82,
                            Address = "Dummy Address No_82",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(12),
                            Email = "dummy82@gmail.com",
                            FirstName = "DummyName_82",
                            IsDeleted = false,
                            LastName = "DummyLastName_82"
                        },
                        new
                        {
                            Id = 83,
                            Address = "Dummy Address No_83",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(35),
                            Email = "dummy83@gmail.com",
                            FirstName = "DummyName_83",
                            IsDeleted = false,
                            LastName = "DummyLastName_83"
                        },
                        new
                        {
                            Id = 84,
                            Address = "Dummy Address No_84",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(38),
                            Email = "dummy84@gmail.com",
                            FirstName = "DummyName_84",
                            IsDeleted = false,
                            LastName = "DummyLastName_84"
                        },
                        new
                        {
                            Id = 85,
                            Address = "Dummy Address No_85",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(40),
                            Email = "dummy85@gmail.com",
                            FirstName = "DummyName_85",
                            IsDeleted = false,
                            LastName = "DummyLastName_85"
                        },
                        new
                        {
                            Id = 86,
                            Address = "Dummy Address No_86",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(41),
                            Email = "dummy86@gmail.com",
                            FirstName = "DummyName_86",
                            IsDeleted = false,
                            LastName = "DummyLastName_86"
                        },
                        new
                        {
                            Id = 87,
                            Address = "Dummy Address No_87",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(43),
                            Email = "dummy87@gmail.com",
                            FirstName = "DummyName_87",
                            IsDeleted = false,
                            LastName = "DummyLastName_87"
                        },
                        new
                        {
                            Id = 88,
                            Address = "Dummy Address No_88",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(45),
                            Email = "dummy88@gmail.com",
                            FirstName = "DummyName_88",
                            IsDeleted = false,
                            LastName = "DummyLastName_88"
                        },
                        new
                        {
                            Id = 89,
                            Address = "Dummy Address No_89",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(47),
                            Email = "dummy89@gmail.com",
                            FirstName = "DummyName_89",
                            IsDeleted = false,
                            LastName = "DummyLastName_89"
                        },
                        new
                        {
                            Id = 90,
                            Address = "Dummy Address No_90",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(49),
                            Email = "dummy90@gmail.com",
                            FirstName = "DummyName_90",
                            IsDeleted = false,
                            LastName = "DummyLastName_90"
                        },
                        new
                        {
                            Id = 91,
                            Address = "Dummy Address No_91",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(51),
                            Email = "dummy91@gmail.com",
                            FirstName = "DummyName_91",
                            IsDeleted = false,
                            LastName = "DummyLastName_91"
                        },
                        new
                        {
                            Id = 92,
                            Address = "Dummy Address No_92",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(53),
                            Email = "dummy92@gmail.com",
                            FirstName = "DummyName_92",
                            IsDeleted = false,
                            LastName = "DummyLastName_92"
                        },
                        new
                        {
                            Id = 93,
                            Address = "Dummy Address No_93",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(54),
                            Email = "dummy93@gmail.com",
                            FirstName = "DummyName_93",
                            IsDeleted = false,
                            LastName = "DummyLastName_93"
                        },
                        new
                        {
                            Id = 94,
                            Address = "Dummy Address No_94",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(56),
                            Email = "dummy94@gmail.com",
                            FirstName = "DummyName_94",
                            IsDeleted = false,
                            LastName = "DummyLastName_94"
                        },
                        new
                        {
                            Id = 95,
                            Address = "Dummy Address No_95",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(58),
                            Email = "dummy95@gmail.com",
                            FirstName = "DummyName_95",
                            IsDeleted = false,
                            LastName = "DummyLastName_95"
                        },
                        new
                        {
                            Id = 96,
                            Address = "Dummy Address No_96",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(60),
                            Email = "dummy96@gmail.com",
                            FirstName = "DummyName_96",
                            IsDeleted = false,
                            LastName = "DummyLastName_96"
                        },
                        new
                        {
                            Id = 97,
                            Address = "Dummy Address No_97",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(62),
                            Email = "dummy97@gmail.com",
                            FirstName = "DummyName_97",
                            IsDeleted = false,
                            LastName = "DummyLastName_97"
                        },
                        new
                        {
                            Id = 98,
                            Address = "Dummy Address No_98",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(64),
                            Email = "dummy98@gmail.com",
                            FirstName = "DummyName_98",
                            IsDeleted = false,
                            LastName = "DummyLastName_98"
                        },
                        new
                        {
                            Id = 99,
                            Address = "Dummy Address No_99",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(66),
                            Email = "dummy99@gmail.com",
                            FirstName = "DummyName_99",
                            IsDeleted = false,
                            LastName = "DummyLastName_99"
                        },
                        new
                        {
                            Id = 100,
                            Address = "Dummy Address No_100",
                            CreatedOn = new DateTime(2023, 11, 28, 14, 59, 5, 835, DateTimeKind.Local).AddTicks(68),
                            Email = "dummy100@gmail.com",
                            FirstName = "DummyName_100",
                            IsDeleted = false,
                            LastName = "DummyLastName_100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
